import { GymPackage, SupportContact } from "./types";

export const GYM_PACKAGES: GymPackage[] = [
  {
    id: "basic",
    name: "GÓI CƠ BẢN",
    nameEn: "BASIC PLAN",
    nameZh: "基础计划",
    durationLabel: "GÓI 1 THÁNG",
    durationLabelEn: "1 MONTH PLAN",
    durationLabelZh: "1个月计划",
    priceValue: "500.000đ",
    description: "Tập luyện tự do, không bao gồm huấn luyện viên",
    descriptionEn: "Free training sessions, personal fitness trainer is not included",
    descriptionZh: "自由训练，不包含私人教练服务",
    features: ["Khóa Locker free", "Phòng xông hơi", "Detox free hằng ngày"],
    featuresEn: ["Free Smart Locker", "Premium Sauna room access", "Complimentary Daily Detox drink"],
    featuresZh: ["免费智能储物柜", "高级蒸汽桑拿房", "每日免费赠送排毒饮品"],
    gradient: "from-zinc-900 via-zinc-800 to-zinc-900",
  },
  {
    id: "standard_6m",
    name: "GÓI TIÊU CHUẨN 6T",
    nameEn: "STANDARD 6M",
    nameZh: "标准6个月",
    durationLabel: "GÓI 6 THÁNG",
    durationLabelEn: "6 MONTHS PLAN",
    durationLabelZh: "6个月计划",
    priceValue: "2.500.000đ",
    description: "Tập luyện tự do, tặng 2 buổi tập với PT",
    descriptionEn: "Free training sessions, includes 2 complimentary 1-1 PT coaching sessions",
    descriptionZh: "自由训练，加赠2节专属1对1 PT私人教练课",
    features: ["Khóa Locker free", "Phòng xông hơi", "Detox free hằng ngày"],
    featuresEn: ["Free Smart Locker", "Premium Sauna room access", "Complimentary Daily Detox drink"],
    featuresZh: ["免费智能储物柜", "高级蒸汽桑拿房", "每日免费赠送排毒饮品"],
    gradient: "from-zinc-900 via-zinc-850 to-zinc-900",
  },
  {
    id: "premium_12m",
    name: "GÓI CAO CẤP 12T",
    nameEn: "PREMIUM 12M",
    nameZh: "高级12个月",
    durationLabel: "GÓI 12 THÁNG",
    durationLabelEn: "12 MONTHS PLAN",
    durationLabelZh: "12个月计划",
    priceValue: "4.500.000đ",
    description: "Tập luyện tự do, tặng 5 buổi PT, có tủ đồ riêng",
    descriptionEn: "Free training sessions, includes 5 complimentary PT sessions & a private personal locker",
    descriptionZh: "自由训练，加赠5节PT私教课，分配专属私人储物箱",
    features: ["Khóa Locker free", "Phòng xông hơi", "Detox free hằng ngày"],
    featuresEn: ["Free Smart Locker", "Premium Sauna room access", "Complimentary Daily Detox drink"],
    featuresZh: ["免费智能储物柜", "高级蒸汽桑拿房", "每日免费赠送排毒饮品"],
    gradient: "from-zinc-900 via-zinc-800 to-zinc-950",
  },
  {
    id: "vip_elite",
    name: "HỘI VIÊN VIP ELITE",
    nameEn: "VIP ELITE MEMBER",
    nameZh: "VIP 精英会员",
    durationLabel: "GÓI 12 THÁNG",
    durationLabelEn: "12 MONTHS PLAN",
    durationLabelZh: "12个月计划",
    priceValue: "12.000.000đ",
    description: "Huấn luyện viên cá nhân 1:1, đầy đủ dịch vụ xông hơi",
    descriptionEn: "Exclusive 1:1 Personal Trainer, premium locker room, and full sauna service access",
    descriptionZh: "1对1私人健身教练全程陪同，享有顶级桑拿沐浴和全身排毒功能",
    features: ["Khóa Locker free", "Phòng xông hơi", "Detox free hằng ngày"],
    featuresEn: ["Free Smart Locker", "Premium Sauna room access", "Complimentary Daily Detox drink"],
    featuresZh: ["免费智能储物柜", "高级蒸汽桑拿房", "每日免费赠送排毒饮品"],
    gradient: "from-neutral-900 via-zinc-900 to-neutral-950",
  },
];

export const SUPPORT_CONTACTS: SupportContact[] = [
  {
    id: "tiep_tan",
    name: "TRẦN THỊ TIẾP TÂN",
    nameEn: "JESSICA RECEPTION",
    nameZh: "陈前台",
    roleLabel: "LỄ TÂN & CHĂM SÓC",
    roleLabelEn: "RECEPTION & SUPPORT",
    roleLabelZh: "前台与客户关怀",
    avatarChar: "T",
    bio: "Xin chào! Tôi là Trần Thị Tiếp Tân. Hãy gửi tin nhắn hỗ trợ để tôi tư vấn kĩ lưỡng nhất cho anh/chị nhé.",
    bioEn: "Hello! I am Jessica from Reception. Please leave me a message so I can consult you in the best possible way.",
    bioZh: "您好！我是客服接待陈前台。如果您有任何疑问，请随时给我留言，我将竭诚为您服务。",
    initialMessage: "Xin chào! Tôi là Trần Thị Tiếp Tân (Lễ tân ca sáng). Tôi trực tổng đài hỗ trợ 24/7, rất vui được tư vấn các dịch vụ dời ca, hoàn tiền, kỹ thuật hoặc dinh dưỡng của bạn. Bạn hãy để lại tin nhắn nhé!",
    initialMessageEn: "Hello! I'm Jessica (morning shift reception). I'm online 24/7. It's a pleasure to assist with class rescheduling, refunds, equipment setup, or dietary consult inquiries. Type your question below!",
    initialMessageZh: "您好！我是前台小陈（早班）。24/7 在线，很高兴协助您办理排课、退款、设备技术及营养咨询。请在下方留下您的问题！",
    category: "support",
    isOnline: true,
  },
  {
    id: "huan_luyen",
    name: "NGUYỄN HUÂN LUYỆN",
    nameEn: "COACH NGUYEN",
    nameZh: "阮教练",
    roleLabel: "HUẤN LUYỆN VIÊN (PT)",
    roleLabelEn: "健身教练 (PT)",
    roleLabelZh: "私人健身教练 (PT)",
    avatarChar: "H",
    bio: "Chào bạn! Tôi là Nguyễn Huấn Luyện - PT trưởng FitGym. Nhắn tin cho tôi để được tư vấn lộ trình độ dáng hoàn toàn miễn phí nhé!",
    bioEn: "Hi! I am Coach Nguyen, Head PT at FitGym. Send a message to get a completely free posture and body composition consultation!",
    bioZh: "您好！我是 FitGym 总教练阮教练。现在与我聊聊，即可获得完全免费的健美体态评估与课程规划！",
    initialMessage: "Chào bạn mới! Tôi là Nguyễn Huấn Luyện, có 6 năm kinh nghiệm cân đối thể trạng và giảm mỡ chuyên sâu. Tôi có thể tư vấn chế độ Bulking, Cutting hoặc thiết kế các bài tập ngực/bụng riêng cho bạn. Cần tôi trợ giúp gì nào?",
    initialMessageEn: "Welcome! I'm Coach Nguyen, with 6 years of expertise in body composition analysis and specialized fat loss. I can consult you on Bulking, Cutting, or customized chest/abs workouts. How can I help you?",
    initialMessageZh: "欢迎新朋友！我是阮教练，拥有6年人体比例微调及全身高效减脂经验。我可以解答您的关于增肌、减脂，以及设计个性化的胸肌/腹部锻炼计划。怎么帮您？",
    category: "pt",
    isOnline: true,
  },
  {
    id: "support_technical",
    name: "LÊ HOÀNG KỸ THUẬT",
    nameEn: "ALEX TECHNICAL",
    nameZh: "黎技术",
    roleLabel: "KỸ THUẬT VIÊN THIẾT BỊ",
    roleLabelEn: "EQUIPMENT TECHNICIAN",
    roleLabelZh: "设备技术专员",
    avatarChar: "K",
    bio: "Hỗ trợ sửa lỗi thiết bị checkin, thẻ từ NFC, tủ locker thông minh.",
    bioEn: "Troubleshoots issues with physical check-in gates, digital NFC passes, and smart automated locker systems.",
    bioZh: "协助解决人脸核验、智能 NFC 会员卡以及全自动电子寄存柜的软件故障和技术维护。",
    initialMessage: "Dạ em chào anh/chị! Em phụ trách bảo dưỡng và nâng cấp hệ thống phần mềm của phòng tập FIT GYM. Anh/chị đang gặp vấn đề gì với thẻ số hay cửa Check-in hả anh/chị?",
    initialMessageEn: "Hello! I am Alex, responsible for maintaining and upgrading the FIT GYM software and pass entry systems. Are you currently experiencing issues with your digital card or check-in scanners?",
    initialMessageZh: "您好！我是黎技术，负责 FIT GYM 会员进门扫码及软件后台系统的升级和维护。您的数字卡或检票闸机目前有出现无法识别的情况吗？",
    category: "support",
    isOnline: false,
  },
];
